---
# vars file for sqlserver
mysql_pkgs:
  - bundler
  - mysql-server-core-5.5
  - mysql-client-core-5.5
  - libmysqlclient-dev
  - python-mysqldb
  - mysql-server
  - mysql-client
  - build-essential
